
import java.awt.Color;
import javax.swing.JOptionPane;




public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_menuSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_menuIzquierdo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton_borrarLuego = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_zonaTrabajo = new javax.swing.JPanel();
        jLabel_velocidadesLargos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menuSuperior.setBackground(new java.awt.Color(204, 0, 51));
        jPanel_menuSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_menu_48px_1.png"))); // NOI18N
        jPanel_menuSuperior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("l");
        jPanel_menuSuperior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 10, 40));

        getContentPane().add(jPanel_menuSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 80));

        jPanel_menuIzquierdo.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_menuIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(100, 100, 100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/account_24px.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Velocidades llenadoras");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 40));

        jPanel_menuIzquierdo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 300, 70));

        jPanel5.setBackground(new java.awt.Color(100, 100, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_borrarLuego.setBackground(new java.awt.Color(100, 100, 100));
        jButton_borrarLuego.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jButton_borrarLuego.setForeground(new java.awt.Color(255, 255, 255));
        jButton_borrarLuego.setText("   VELOCIDADES LLENADORAS");
        jButton_borrarLuego.setBorderPainted(false);
        jButton_borrarLuego.setContentAreaFilled(false);
        jButton_borrarLuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_borrarLuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_borrarLuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_borrarLuegoMouseExited(evt);
            }
        });
        jPanel5.add(jButton_borrarLuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        jPanel_menuIzquierdo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        jPanel6.setBackground(new java.awt.Color(100, 100, 100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("nº envases");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 40));

        jPanel_menuIzquierdo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 70));

        jPanel7.setBackground(new java.awt.Color(100, 100, 100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel10.setText("tomate fresco");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 40));

        jPanel_menuIzquierdo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 70));

        getContentPane().add(jPanel_menuIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 570));

        jPanel_zonaTrabajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_velocidadesLargos.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel_velocidadesLargos.setText("Velocidades llenadoras");
        jLabel_velocidadesLargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_velocidadesLargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_velocidadesLargosMouseEntered(evt);
            }
        });
        jPanel_zonaTrabajo.add(jLabel_velocidadesLargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 40));

        getContentPane().add(jPanel_zonaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 990, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_velocidadesLargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_velocidadesLargosMouseEntered
        

        
        
        
        
        
    }//GEN-LAST:event_jLabel_velocidadesLargosMouseEntered

    private void jButton_borrarLuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_borrarLuegoMouseEntered
        
   
        jButton_borrarLuego.setForeground(Color.BLUE);
        
        
    }//GEN-LAST:event_jButton_borrarLuegoMouseEntered

    private void jButton_borrarLuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_borrarLuegoMouseExited
        jButton_borrarLuego.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton_borrarLuegoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_borrarLuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_velocidadesLargos;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_menuIzquierdo;
    private javax.swing.JPanel jPanel_menuSuperior;
    private javax.swing.JPanel jPanel_zonaTrabajo;
    // End of variables declaration//GEN-END:variables
}
